// 导出 / Overleaf 相关工具（写操作，默认需确认）。

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * @param {{
 *   getPaper: () => { title?: string, path?: string, pages?: string[] } | null,
 *   getWorkspace: () => object,
 *   saveMarkdownFile?: (payload: { defaultName: string, content: string }) => Promise<{ ok: boolean, filePath?: string, canceled?: boolean, error?: string }>,
 *   openExternal?: (url: string) => Promise<void> | void,
 *   writeClipboard?: (text: string) => Promise<void> | void,
 * }} deps
 */
export function createExportToolDefs(deps = {}) {
  const {
    getPaper,
    getWorkspace,
    saveMarkdownFile,
    openExternal,
    writeClipboard,
  } = deps;

  return [
    {
      name: 'export_markdown_report',
      description: '将 Markdown 报告保存为本地 .md 文件（弹出保存对话框）。用于组会稿、深读报告、调研纪要导出。',
      requiresConfirmation: true,
      parameters: {
        type: 'object',
        properties: {
          title: { type: 'string', description: '文件标题（用于默认文件名）' },
          content: { type: 'string', description: '完整 Markdown 正文' },
        },
        required: ['content'],
      },
      run: async ({ title, content }) => {
        if (typeof saveMarkdownFile !== 'function') throw new Error('导出不可用');
        const paper = getPaper?.();
        const base = String(title || paper?.title || 'paperlens-report')
          .replace(/\.pdf$/i, '')
          .replace(/[\\/:*?"<>|]+/g, ' ')
          .trim()
          .slice(0, 60) || 'paperlens-report';
        const body = String(content || '').trim();
        if (!body) throw new Error('content 为空');
        const result = await saveMarkdownFile({
          defaultName: `${base}.md`,
          content: body.endsWith('\n') ? body : `${body}\n`,
        });
        if (result?.canceled) return { saved: false, canceled: true };
        if (!result?.ok) throw new Error(result?.error || '保存失败');
        return { saved: true, filePath: result.filePath };
      },
    },
    {
      name: 'prepare_overleaf_section',
      description: '生成可粘贴进 Overleaf 的 LaTeX section 草稿，复制到剪贴板，并可选打开已配置的 Overleaf 项目链接。不直接改远程工程（安全）。',
      requiresConfirmation: true,
      parameters: {
        type: 'object',
        properties: {
          sectionTitle: { type: 'string', description: 'section 标题，如 Related Work' },
          latexBody: { type: 'string', description: 'LaTeX 正文（不含外层 document）' },
          openProject: { type: 'boolean', description: '是否打开已配置的 Overleaf 项目，默认 true' },
        },
        required: ['latexBody'],
      },
      run: async ({ sectionTitle, latexBody, openProject = true }) => {
        const title = String(sectionTitle || 'Section').slice(0, 120);
        const body = String(latexBody || '').trim();
        if (!body) throw new Error('latexBody 为空');
        const tex = [
          `% Generated by PaperLens Research Agent`,
          `\\section{${escapeLatexTitle(title)}}`,
          body,
          '',
        ].join('\n');
        if (typeof writeClipboard === 'function') {
          await writeClipboard(tex);
        }
        const ws = getWorkspace?.() || {};
        const url = ws.overleaf?.enabled && ws.overleaf?.projectUrl ? ws.overleaf.projectUrl : '';
        let opened = false;
        if (openProject && url && typeof openExternal === 'function') {
          await openExternal(url);
          opened = true;
        }
        return {
          copied: true,
          chars: tex.length,
          openedOverleaf: opened,
          projectUrl: url || null,
          preview: tex.slice(0, 400),
          hint: opened
            ? '已复制 LaTeX 并打开 Overleaf，请在工程中粘贴。'
            : (url ? '已复制 LaTeX。' : '已复制 LaTeX。可在设置中配置 Overleaf 项目链接以便一键打开。'),
        };
      },
    },
    {
      name: 'export_bibtex_stub',
      description: '根据标题/作者/年份生成简易 BibTeX 条目草稿并复制到剪贴板（需人工核对）。',
      requiresConfirmation: true,
      parameters: {
        type: 'object',
        properties: {
          citeKey: { type: 'string' },
          title: { type: 'string' },
          authors: { type: 'string', description: 'and 分隔的作者' },
          year: { type: 'string' },
          url: { type: 'string' },
        },
        required: ['title'],
      },
      run: async ({ citeKey, title, authors, year, url }) => {
        const key = String(citeKey || slugCiteKey(title) || 'ref').slice(0, 40);
        const lines = [
          `@article{${key},`,
          `  title={${String(title || '').replace(/[{}]/g, '')}},`,
          authors ? `  author={${String(authors).replace(/[{}]/g, '')}},` : null,
          year ? `  year={${String(year).replace(/\D/g, '').slice(0, 4)}},` : null,
          url ? `  url={${String(url).slice(0, 300)}},` : null,
          `  note={Generated by PaperLens — verify before use}`,
          `}`,
        ].filter(Boolean);
        const bib = `${lines.join('\n')}\n`;
        if (typeof writeClipboard === 'function') await writeClipboard(bib);
        return { copied: true, citeKey: key, bibtex: bib };
      },
    },
  ];
}

function escapeLatexTitle(title) {
  return String(title || '').replace(/[\\{}&#$%_]/g, (c) => `\\${c}`);
}

function slugCiteKey(title) {
  return String(title || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '')
    .slice(0, 24) || 'ref';
}

/** 测试用：不依赖 dialog 的直接写文件 */
export function writeMarkdownToPath(filePath, content) {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(filePath, content, 'utf8');
  return { ok: true, filePath };
}

export function buildOverleafSectionTex({ sectionTitle, latexBody }) {
  const title = String(sectionTitle || 'Section').slice(0, 120);
  const body = String(latexBody || '').trim();
  return [
    `% Generated by PaperLens Research Agent`,
    `\\section{${escapeLatexTitle(title)}}`,
    body,
    '',
  ].join('\n');
}
